### ISSUE TITLE
cannot execute: required file not found

### ISSUE THREAD

**Issue by RustyReich** [dmadisetti/steam-tui#58] opened 2023-07-05 18:54 UTC
Every time I try to launch the provided binary, I get the error `bash: ./steam-tui: cannot execute: required file not found`. I am on Ubuntu 23.04.

**Comment by dmadisetti** [comment] 2023-07-24 16:00
Can you do a `ldd steam-tui`? Might be bad libraries. Where did you get the binary?

**Comment by dmadisetti** [comment] 2023-07-24 16:01
Might just be dupe of #54

**Comment by dmadisetti** [comment] 2023-07-24 16:02
Woops. just meant to comment,

**Comment by OracleToes** [comment] 2023-08-29 07:23
I'm getting this same error, here is the output of `ldd steam-tui`

linux-vdso.so.1 (0x00007fff434a9000)
        libssl.so.1.1 => /usr/lib/libssl.so.1.1 (0x00007fe53c915000)
        libcrypto.so.1.1 => /usr/lib/libcrypto.so.1.1 (0x00007fe53be00000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007fe53c8f0000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007fe53c113000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007fe53ba00000)
        /nix/store/mhhlymrg2m70r8h94cwhv2d7a0c8l7g6-glibc-2.34-210/lib/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007fe53c9dd000)

**Comment by JupiLogy** [comment] 2023-11-06 18:35
I fixed this by just copying the `ld-linux-x84-64.so.2` into the "expected" nix directory

**Closed** 2024-05-24 01:17 UTC
Labels: next release, binary / distribution
